development:
  adapter: postgresql
  encoding: unicode
  database: versed-main
  pool: 5
  username: versed
  password: versed
  host: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: versed-main-test
  pool: 5
  username: versed
  password: versed
  host: postgres
